name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Astro site
        run: npm run build
      
      - name: Verify environment
        run: |
          echo "Checking Cloudflare credentials..."
          if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
            echo "ERROR: CLOUDFLARE_API_TOKEN is not set"
            exit 1
          fi
          if [ -z "$CLOUDFLARE_ACCOUNT_ID" ]; then
            echo "ERROR: CLOUDFLARE_ACCOUNT_ID is not set"
            exit 1
          fi
          echo "Credentials are set ✓"
          echo "Account ID: ${{CLOUDFLARE_ACCOUNT_ID:0:8}}..."
      
      - name: Deploy to Cloudflare Pages
        run: |
          echo "Deploying to Cloudflare Pages..."
          echo "Project name: example-1-82932355"
          echo "Account ID: ${{CLOUDFLARE_ACCOUNT_ID:0:8}}..."
          npx wrangler pages deploy dist --project-name=example-1-82932355
